<?php

namespace Colorgreen\Generator\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Validator;

/**
 * Class BaseModel
 * @package Colorgreen\Generator\Models
 * @property array $rules
 * @property array $errors
 */
class BaseModel extends Model
{
    protected static $rules = [];

    protected static $messages = [];


    public function validate($data)
    {
        $v = Validator::make($data, static::$rules, static::$messages);

        if ($v->fails())
        {
            $this->setErrors($v->messages());
            return false;
        }

        return true;
    }


    public function save( array $options = [] )
    {
        if( !$this->validate($this->attributes) )
            return false;
        return parent::save( $options ); // TODO: Change the autogenerated stub
    }


    protected function setErrors($errors)
    {
        $this->errors = $errors;
    }

    public function getErrors()
    {
        return $this->errors;
    }

    public function hasErrors()
    {
        return ! empty($this->errors);
    }
}
